from inputFiles import parameters


def writeEngineFile(massFlowRate, specificImpulse, averageThrust, maximumThrust, tankLength, wetMass, dryMass, timestampList, cgList, thrustList, propellantMassList):  #TODO: write to string first and then single file write
	with open(parameters.engineFileName, "w") as file:
		file.write('<engine-database>')
		file.write('\n  <engine-list>')
		file.write('\n    <engine  ')
		file.write('mfg="' + str(parameters.engineManufacturer) + '" ')
		file.write('code="' + str(parameters.engineName) + '" ')
		file.write('Type="Liquid" ')
		file.write('dia="' + str(int(parameters.displayedSystemDiameter * 1000)) + '" ')
		file.write('len="' + str(int(tankLength * 1000)) + '" ')
		file.write('initWt="' + str(int(wetMass * 1000)) + '" ')
		file.write('propWt="' + str(int((wetMass - dryMass) * 1000)) + '" ')
		file.write('delays="0" ')
		file.write('auto-calc-mass="' + str(parameters.automaticMassCalculation) + '" ')
		file.write('auto-calc-cg="0" ')
		file.write('avgThrust="' + str(averageThrust) + '" ')
		file.write('peakThrust="' + str(maximumThrust) + '" ')
		file.write('throatDia="0" ')
		file.write('exitDia="' + str(0 * 1000) + '" ')
		file.write('Itot="' + str((massFlowRate * parameters.burnDuration) * specificImpulse * 9.81) + '" ')
		file.write('burn-time="' + str(parameters.burnDuration) + '" ')
		file.write('massFrac="0" ')
		file.write('Isp="' + str(specificImpulse) + '" ')
		file.write('tDiv="10" ')
		file.write('tStep="-1." ')
		file.write('tFix="1" ')
		file.write('FDiv="10" ')
		file.write('FStep="-1." ')
		file.write('FFix="1" ')
		file.write('mDiv="10" ')
		file.write('mStep="-1." ')
		file.write('mFix="1" ')
		file.write('cgDiv="10" ')
		file.write('cgStep="-1." ')
		file.write('cgFix="1">')
		file.write('\n      <data>')
		for n, i in enumerate(timestampList):
			file.write('\n        <eng-data ')
			file.write('cg="' + str(cgList[n] * 1000) + '" ')
			file.write('f="' + str(thrustList[n]) + '" ')
			file.write('m="' + str(propellantMassList[n]) + '" ')
			file.write('t="' + str(timestampList[n]) + '"/>')
		file.write('\n      </data>')
		file.write('\n    </engine>')
		file.write('\n  </engine-list>')
		file.write('\n</engine-database>')
		print("File Generation Complete")
