import inputData as data


def writeEngineFile(mdot, isp, Thav, Thmax, ltot, mtot, mdry, tlist, cglist, thrustlist, masslist):  #TODO: write to string first and then single file write
	with open(data.outputfile, "w") as file:
		file.write('<engine-database>')
		file.write('\n  <engine-list>')
		file.write('\n    <engine  ')
		file.write('mfg="' + str(data.Prod) + '" ')
		file.write('code="' + str(data.Enginename) + '" ')
		file.write('Type="Liquid" ')
		file.write('dia="' + str(int(data.Ddis * 1000)) + '" ')
		file.write('len="' + str(int(ltot * 1000)) + '" ')
		file.write('initWt="' + str(int(mtot * 1000)) + '" ')
		file.write('propWt="' + str(int((mtot - mdry) * 1000)) + '" ')
		file.write('delays="0" ')
		file.write('auto-calc-mass="' + str(data.am) + '" ')
		file.write('auto-calc-cg="0" ')
		file.write('avgThrust="' + str(Thav) + '" ')
		file.write('peakThrust="' + str(Thmax) + '" ')
		file.write('throatDia="0" ')
		file.write('exitDia="' + str(0 * 1000) + '" ')
		file.write('Itot="' + str((mdot * data.burntime) * isp * 9.81) + '" ')
		file.write('burn-time="' + str(data.burntime) + '" ')
		file.write('massFrac="0" ')
		file.write('Isp="' + str(isp) + '" ')
		file.write('tDiv="10" ')
		file.write('tStep="-1." ')
		file.write('tFix="1" ')
		file.write('FDiv="10" ')
		file.write('FStep="-1." ')
		file.write('FFix="1" ')
		file.write('mDiv="10" ')
		file.write('mStep="-1." ')
		file.write('mFix="1" ')
		file.write('cgDiv="10" ')
		file.write('cgStep="-1." ')
		file.write('cgFix="1">')
		file.write('\n      <data>')
		for n, i in enumerate(tlist):
			file.write('\n        <eng-data ')
			file.write('cg="' + str(cglist[n] * 1000) + '" ')
			file.write('f="' + str(thrustlist[n]) + '" ')
			file.write('m="' + str(masslist[n]) + '" ')
			file.write('t="' + str(tlist[n]) + '"/>')
		file.write('\n      </data>')
		file.write('\n    </engine>')
		file.write('\n  </engine-list>')
		file.write('\n</engine-database>')
		print("File Generation Complete")
